name: Code Coverage

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest pytest-cov coverage
      
      - name: Run tests with coverage
        run: |
          cd backend
          python -m pytest --cov=app --cov-report=term --cov-report=xml --cov-report=lcov
          mkdir -p ../reports
          mv .coverage* ../reports/ || true
          mv coverage.xml ../reports/ || true
          mv coverage.lcov ../reports/lcov.info || true
      
      - name: Display coverage summary
        run: |
          echo "Coverage Summary:"
          cat reports/coverage.xml | grep -A 3 "<coverage"
      
      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./reports/lcov.info