name: Lint Python Code

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:
    branches:
      - main

jobs:
  pylint:
    name: Run pylint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r backend/requirements.txt

      - name: Run pylint
        run: |
          find backend -type f -name '*.py' -print0 | xargs -0 pylint
